//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganazerLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrganazerEntities : DbContext
    {
        public OrganazerEntities()
            : base("name=OrganazerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ScheduleDb> ScheduleDb { get; set; }
        public virtual DbSet<SubjectDb> SubjectDb { get; set; }
        public virtual DbSet<TaskaDb> TaskaDb { get; set; }
    }
}
