//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganazerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskaDb
    {
        public int id { get; set; }
        public int status { get; set; }
        public string attachmensFiles { get; set; }
        public int idSubject { get; set; }
        public System.DateTime dataFinish { get; set; }
    
        public virtual SubjectDb SubjectDb { get; set; }
    }
}
